### ISSUE TITLE
Meta keys not sent when using Remote Desktop

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3900]
**Imported issue:**
- Author: Josh Gee
- Date: 2014-03-21 10:48:23
- Legacy ID: 3970

**Steps to reproduce:**
1. Install Windows 8 as Server with either latest stable 1.4.16 or nightly 1.4.17 r2043 x64
2. Install Mac OSX 10.8.4 with matching version
3. Open Microsoft Remote Desktop 8.0.5 to another machine from the Mac Client.
4. Open any app in the RDP Session
5. NO meta keys function (Shift, Alt, Ctrl) are sent through the remote desktop session.

Expected: 
Expect all meta keys to function within the RDP session, just like they do outside the session.

Actual: 
No meta keys function in the RDP session.  However, meta keys DO function in the Remote Desktop App itself (in the session config screens, etc.).  But within the session, none of them work.

**Affected versions**
- Server: Windows 8 x64 all patches - Synergy 1.4.17 r2043
- Client: OSX 10.8.4 all patches - Synergy 1.4.17 r2043
- Microsoft Remote Desktop Client 8.0.5
- RDP Session destination: Windows Server 2008 R2

Keyboard mappings in use:
- Win 8 Server: US Dvorak
- Mac Client: US Dvorak
- RDP remote host: US Dvorak 

**Temporary workarounds:**

None found thus far.

**Similar bugs:**

Several similar bugs exist, some quite old:
- System-wide issue: http://synergy-foss.org/spit/issues/details/3689/
- VMWare Fusion: http://synergy-foss.org/spit/issues/details/3153/
- VMWare Workstation: http://synergy-foss.org/spit/issues/details/19/
- Eve Online Client: http://synergy-foss.org/spit/issues/details/3331/
- Right shift only problems: 
  - http://synergy-foss.org/spit/issues/details/2799/
  - http://synergy-foss.org/spit/issues/details/242/

**Additional comments:**

I'm guessing that some programs are interpreting the keyboard at a scan-code level rather than an character level.  I suspect this because I've noticed in the past that when I RDP from any machine (Mac or Windows, even without Synergy) to a remote machine with a different keyboard layout (US English or UK English) that my Dvorak keyboard is not always correctly mapped unless the remote machine is also configured with a Dvorak mapping.  So RDP seems to send scan codes rather than characters.  I've had similar issues using the VMWare Vsphere client from a Windows machine to Windows Servers.  

Since many of the related bugs all seem to refer to similar types of applications (hardware emulation), this might point to a common source for these problems.

**Comment by andrewr01** [comment]
Would love for this issue to be fixed! Might try 1.4.16 stable.

**Comment by andrewr01** [comment]
1.4.16 doesn't work either, does anyone know of a version that does work?
* Windows 8.1 Update 1 = Server
* OS X Yosemite 10.10.2 = Client
* Microsoft Remote Desktop 8.0.13 (Build 25377)
* Synergy 1.4.16

**Comment by ddikman** [comment]
I get something similar in my setup. I've got:
PC 1: Windows 8, Synergy 1.6.3 running RDP against a VM (server)
PC 2: Windows 7, Synergy 1.6.2

When I'm in the RDP session (having the 'Apply windows key combinations' setting enabled) the windows key shortcuts are applied on the PC 1 instead of the RDP session. If I stop synergy they work in the RDP again.

**Comment by jwelch222** [comment]
Also seeing this issue. Windows 7 64 bit server, OS X 10.10.3 client.

**Comment by Mystikite** [comment]
Still seeing this issue after upgrading to 1.7.1
Server: Win 7 64bit (1.7.1)
Client: OSX 10.10 (1.7.1)

**Comment by YoniGit** [comment]
Temporary work around is to download the old "Remote Desktop Connection" App from microsoft:
http://www.microsoft.com/en-us/download/details.aspx?id=18140
This is the old version, has less features and is not ideal, but at least this issue is not exhibited. It would be nice to get a fix for this.

I can still see the issue with my standard setup:
Server: Win 7 x32 (1.7.1)
Client: OSX 10.10.2 Yosemite (1.7.1)
Application: Microsoft Remote Desktop (Installed from the App Store)

**Comment by Manksgloob** [comment]
Confirmed the same issue remains after upgrading Synergy to 1.7.2 on both server and client.
Server: Windows 10 64-bit, preview build 10074
Client: Mac OS X 10.10.4, preview build 14E11f

I wish I could use the work-around with older RDC client but the remote machines that I connect to have higher security requirements that are only supported by the latest version of Microsoft Remote Desktop client from the Mac App Store.

**Comment by djkouza** [comment]
Seeing same stuff here as well on 1.7.3
Server: Windows 7 64bit 
Client: Mac OS X 10.10.2
Also another big issue is that my Shift key doesn't send to the RDP software, making typing an e-mail difficult.

**Comment by phampton24** [comment]
I am experiencing the same issue on Synergy Version 1.7.4
Server:  Windows 10 64 Bit
Client: Mac OSX 10.10.5
RDP From Client to another Windows box and no control keys (CTRL, ALT, SHIFT, WIN) are sent over RDP

**Comment by dgtlcopywrite** [comment]
Same here on Synergy 1.7.4.
Server: Windows 7 x64 or Windows 10 x64
Client: Mac OS X 10.11
RDP from Synergy Client to Windows machine, no modifier keys are sent over RDP from Synergy Server.

I would really like to see this fixed. The old Microsoft RDP client is pretty buggy on newer OS X's, so I'm using RDP from my windows virtual machine as a work around.

**Comment by matthewmatician** [comment]
Same here on Synergy 1.7.4
Server: Mac OS X 10.10.5
Client: Mac OS X 10.10.5 
RDP to windows machine. Zero Modifiers being passed.

**Comment by andrewr01** [comment]
Just tried the Parallels 2X RDP client and it works! All meta keys working great! Definitely check it out.

**Comment by tomsherrod** [comment]
Same here on Synergy 1.7.5
Server: Ubuntu 14.04
Client: Mac OS X 10.9.5
RDP to windows machine, no shift keys

**Comment by nickderoo** [comment]
also suffering from this, 
Server: Fedora 18
Client Mac OSx 10.11.12
RDP to windows no dice, if anyone has any other workarounds i'd love to hear about it.

**Comment by andrewr01** [comment]
@nickderoo: Parallels 2X RDP client.

**Comment by Snooper1989** [comment]
Also suffering this on 1.7.5
Server: Windows 10
Client: Mac OS X 10.10.5
RDP to windows machine, no meta keys

**Comment by andrewr01** [comment]
@snooper1989: Parallels 2X RDP client.

**Comment by kyrsjo** [comment]
Seeing the same with v1.7.4, client OsX 10.11.2, server CentOS 7.1, RDP client "Microsoft Remote Desktop" to windows 2008R2 server. It also happens in the login prompt, which is somewhat surprising. Possible workaround is to use CapsLock, provide the password in the config dialog of the app, or reach over to the keyboard physically connected to the mac.

**Comment by andrewr01** [comment]
@kyrsjo Have you tried the Parallels 2X RDP client? It works!

**Comment by TryTryAgain** [comment]
This is also an issue for me, when using a Linux/Ubuntu host (Windows/Dell keyboard) and a Mac OSX 10.11.4 (has been an issue since 10.10.x) and trying to interact with a Microsoft Remote Desktop RDP session on that Mac. Something to note, this was not and is still not an issue when using CoRD as my RDP client, but CoRD is pretty crashy nowadays. I'd like it to work no matter what I use.

**Comment by derbbre** [comment]
Still an issue. Windows server (1.8.2) Mac client (1.8.2). Microsoft Remote Desktop (8.0.32).

**Comment by Corona4456** [comment]
This is still an issue. Ubuntu - Server & Mac - Client (both on 1.8.3).

**Comment by MDScranton** [comment]
I am still having this issue as well with Windows 10 as Server and macOS as Client. It's not as big of a deal for me since my Mac is generally on the same desk as the keyboard I'm using, but it would be fantastic if I didn't have to use the Mac keyboard at all.

**Comment by botsmack** [comment]
Still having this issue.

Synergy: 1.8.6-stable-2ab21aa
Server: Windows 10
Client: macOS 10.12.2

Using RD Version 8.0.36 (Build 27228) and it won't pass meta keys.

**Comment by alanhoyle** [comment]
I'm seeing this with Synergy 1.8.6 client (macOS Sierra 10.12.3) and server (Ubuntu 16.04), both with latest updates. Remote Desktop 8.0.37 (app store version).

The remote desktop won't even receive shift/ctrl/alt.

**Comment by alanhoyle** [comment]
Updated macOS Sierra client and Ubuntu server to Synergy 1.8.7 and the problem remains.

**Comment by ericrdgz** [comment]
Using Synergy 1.8.7 on macOS Sierra and Windows 10. I am also facing this problem. Please look into it. Makes using the shift and command key in RDP impossible to use.

**Comment by ppkamik** [comment]
Not working for me either *synergy 1.8.7* (no SHIFT key):
Server: CentOS7
Client: Sierra 10.12.3
Apps in client:
MS Remote Desktop 8.0.37 
Parallels Desktop 12.1.3

**Comment by ussjoin** [comment]
Also seeing the same issue. 
Server: OSX 10.10.5
Client: OSX 10.11.6
Apps in client:
MS Remote Desktop 8.0.37

**Comment by EasyAsABC123** [comment]
same issue if using screenhero and all vm tools or remote desktop/vnc...didn't test on ssh

**Comment by taylorsmcclure** [comment]
I first had this issue about 2 years ago, found it is still affecting me with my setup D:

Synergy is awesome otherwise, but I would really like it to work in this use case.

**Comment by Mystikite** [comment]
Same story. 2 years later, same bug still breaking my workflow.  not really complaining, just letting you know there is a user base still being hit by this issue.  a label of 'v1.10-could' doesn't inspire much hope that this issue will make the cut.

**Comment by sixsixtrample** [comment]
I am also experiencing this issue now that I need to RDP to a windows machine from my mac synergy client. 

I love Synergy, but I won't be able to keep using it if I can't get this to work. I'll have to switch back to a KVM (blech)

**Comment by johnweldon** [comment]
still seeing this:

Synergy Server: 1.8.8-stable-25a8cb2  Windows 10 64bit
Synergy Client: 1.8.8-stable-25a8cb2 macOS Sierra 10.12.4
RDP Client on OSX: Microsoft Remote Desktop 8.0.38 (build 27253)
Remote RDP Server: Windows Server 2008 R2 Enterprise SP 1

Left, Right Shift keys don't work
Windows Key doesn't work

If I use the OSX keyboard directly it works

**Comment by Mystikite** [comment]
Same Issue.  This has prevented me from recommending this software to several family members.  While i am able to deal w/ the frustration, they aren't as tech savvy, and expect a product should just work.

**Comment by ajovedel** [comment]
I am also having same issue with synergy client and server on 1.8.8 and using Win10 as server and MacOS 10.12.6. It is very annoying as it stops me from using synergy when using RDP.

**Comment by zekyl314** [comment]
Any updates on this?

**Comment by TryTryAgain** [comment]
It's unfortunate, I can no longer recommend this product, and have stopped using it myself...back to multiple keyboards and mice until this is resolved, very sad.

**Comment by Mystikite** [comment]
What does the 'legacy' tag denote?
Can we hope this issue is fixed in the upcoming 2.0 release?
And if not, what becomes of the 1.10 release that this issue was tagged as '1.10-could'?

I telecommute, and this bug impacts me daily.
Imagine trying to do remote work when completely unable to use the SHIFT key.

**Comment by justinkauai** [comment]
I found using xfreerdp works best.  Now my problem is the command key is the modifier e.g cmd + c.

On my mac I have the command = control
control = command

**Comment by zekyl314** [comment]
Does this mean this is no longer going to be fixed and the bug will remain in all future versions?  I still have this issue.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.
