### ISSUE TITLE
UHD/4K DPI scaling broken on Windows server

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4041]
**Imported issue:**

* Author: James White
* Date: 2014-07-22 21:50:56
* Legacy ID: 4111
* Version: 1.5.0

Since an unspecified update to Windows 8.1 (I can't track the exact update at this time) Synergy 1.5 and 1.5.1 no longer works properly when a HiDPI device is configured as the server. In my case I'm using a Dell XPS 9530 running Windows 8.1 Update 1 with all the latest updates, with a screen resolution of 3200 x 1800 using DPI scaling. 

What happens on all clients in my setup (regardless of Operating System) is when the focus is moved to said client, the mouse cursor immediately jumps to the bottom right hand side of the screen and becomes stuck, it cannot move, but mouse buttons and keyboard input are still correctly captured. Unfortunately, the only way to unstick the mouse is to kill the Synergy client software on the client machine. Because of this Synergy has now become unusable on my setup.

**Steps to reproduce:**

1. Setup a Windows device as the Synergy server using a DPI scaling factor greater than 100%
2. Connect any client, which can be Windows, Mac OS X or Linux (this bug is dependant on the server)
3. Move the mouse cursor towards the client to switch the focus

Expected: Mouse should be able to move freely on the client as normal

Actual: On focus on the client the mouse immediately gets placed in the bottom right hand corner of the client screen and becomes stuck, unable to move.

**Versions and operating systems:**

Tested with the following setup:

Windows 8.1 with 200% scaling (Server)

Ubuntu 14.04 normal DPI (Client)

Windows 8.1 normal DPI (Client)

**Temporary workarounds:**

*Best workaround:*

Disable Desktop Scaling for all users on the synergys.exe.

To do this, go to the installer directory of Synergy, this is usually:

C:\Program Files\Synergy or C:\Program Files (x86)\Synergy

Locate synergys.exe, right click on the executable and click properties. Select the compatibility tab and click "Change settings for all users". Tick the Disable scaling on high DPI settings" tick box and apply the settings. Restart the synergys.exe via the GUI or via services.msc.

This should give you normal functionality back without the mouse sticking in the corner, noticeable side affects of this workaround appear to be the mouse speed being faster on the client.

**Credit to Christian Liebscher for finding this workaround.**

*Other workarounds:*

Disable Desktop Scaling i.e. switch to 100%. (Note: this will be not be possible on high resolution devices, because the UI will be tiny)

Spaces out clients displays and disable automatic switching. Use user defined keystrokes. See http://superuser.com/a/771618 for more info.

Do not configure a Windows device that is using DPI scaling as the server, designate an alternative device as the server and connect as a client.

**Similar bugs:**

None.

**Additional comments:**

This problem initially wasn't present but as occurred more recently. It is likely that an update via Windows Update has broken this or an API change related to DPI is the cause.

**Comment by the-wes** [comment]
I think similar issues happen with other OSes as server as well.

**Comment by keeran** [comment]
Having the same issue and unable to disable display scaling on synergys.exe (option is disabled).

**Comment by fuzzzerd** [comment]
I see the workaround, but the bug is closed. Is there a planned fix for this or is the workaround posted above the long-term fix?

**Comment by PtrDr** [comment]
Hi fuzzerd:  I don't know if the Synergy people are working on this, but I recently added the workaround suggested by mabott to the other settings with the synergys.exe file:

 "Control Panel->Appearance and Personalization->Display, click Set Custom text size (DPI) on the left sidebar, then check the "Use Windows XP style DPI scaling". "

That, with the other settings I previously reported, gets Synergy back to "normal" .The problem with the open windows of certain programs seems to have gone away. Of course, that is just my own particular set-up, and may be of no use to others. I still do not know what provoked it in the first place as I had not touched those settings for a long time.  I hope that Synergy support gurus are still trying to find the root of the problem.

**Comment by PtrDr** [comment]
Oops! I spoke too soon. 

While it is true that Synergy works now as expected, the change to the Win XP DPI scaling wreaks havoc on a number of programs -- in particular by shrinking down the type in the programs to an unreadable small font size. So I have unchecked that setting again, so that I can see what I am doing.  I do not really have the time to mess around with the font settings in half-a-dozen programs that I use frequently...

I hope that this bug is not "closed" but actively being pursued.

Peter

**Comment by fuzzzerd** [comment]
This is exactly the issue; it works fine if you disable DPI scaling for the entire operating system, but on devices with high dpi that is not a solution, because as you mention sizes of screen elements are too small to see.

I have not yet tested out the settings specifically on the DPI settings for the synergy service; but even still that seems like a poor solution to a problem. Some how mouse without borders doesn't have this issue. While that's a separate topic, it seems like there has to be a way to fix this inside the synergy service.

**Comment by the-wes** [comment]
PtrDr - I am not sure where you're seeing this bug is closed, it is very open and high priority for Synergy.

fuzzzerd - Of course, the workarounds are not in any way intended to be the "fix" for the issue. It's just to get us by until we can find a good permanent solution.

**Comment by PtrDr** [comment]
the-wes:  Thanks for the clarification. I see a Closed button beside  "Cursor jumps down and to the right #4016"   on  Jan 1m Maybe  that refers to a different, but related topic, that perhaps has been rolled into this one?  Anyway, i am very glad that someone much smarter than I am is working on it  :)  Best luck to those toiling away on it.

**Comment by chriseng** [comment]
Thanks for the workaround. It works great using my Surface Pro 3 as the Synergy server.

**Comment by PtrDr** [comment]
Still a problem for me, and interferes with my work frequently every day. I notice that the following programs, (which I use constantly) are the most problematic:

Pegasus email Client
Chaos and Intellect (PIM and PIM with email) from Chaos Software
Quicken Home and Business 2012

The problem only occurs when I have a window of any one of those programs open. If the windows are minimized, I can have all three programs running, and be using something else; in that case, there is no problem.

This is all on Windows 7 Pro 64 bit; no Win 8 or other stuff.

Hoping for a fix soon!

**Comment by mikehc** [comment]
I have this issue my client is a MBP 2014 and server Surface Pro 3. I tried the workaround about setting the app to not support High DPI but is not working. If I invert the configuration (Mac -> Server and SP3 -> Client) things seems to ok.

**Comment by PtrDr** [comment]
As far as I can tell, the issue remains unresolved. The recent upgrades still have not addressed this problem, so it continues. As it was interfering so frequently with my work, I grudgingly switched over to Mouse without Borders, which I am now using. It is not perfect, and has a couple of quirks, but they  do not cause me any problems that are not easily handled. 

Interestingly, if I use the mouse and keyboard which are attached to the computer which is usually my Client machine, I can use that mouse and keyboard on both computers. I don't, mostly, but it works just as well. Most importantly, Mouse without Borders does not freeze up my server computer as Synergy was doing.

If the issue can be dealt with, I will happily come back to Synergy, and continue to support the program.

**Comment by mikehc** [comment]
@PtrDr Thanks for your recommendation. I end up using MouseShare because of my mixed environment. Unfortunately this is not the only issue that impact my workflow, there's a nasty bug when computers have different keyboard layouts too.

**Comment by irlemos** [comment]
Same issue here, mouse stuck on linux client.
Using Windows 8.1 as server and a linux machine as client, both with dual monitor setup. Nightly build for today (1.7.4).

Problem resolved by setting DPI scale to 100% on Windows.
Thank you for all the feedbacks.

Still, Synergy need a fix, as everything is too small for me on Windows with this DPI setting.

**Comment by Dippyskoodlez** [comment]
Got this same problem on 8.1pro and Win10 insider preview.

**Comment by sidewinder94** [comment]
Additional info : 

On a 8.1 Server, synergy 1.7.3 (both client and server) (same laptop as the first post) with an additional screen connected (1680x1050) placed at the right of the main screen and the synergy client (Win 8.1 1920x1080 screen) configured to be on the top of the main screen.

When trying to get to the client with synergy, the mouse will jump back to the top of the second screen.

Seems related since the first workaround still works with this issue as well

**Comment by PtrDr** [comment]
It seems as though this issue is still dogging Synergy. In my case, (two Windows 7 computers with two same-model  Samsung screens)) none of the workarounds work.

**Comment by sidewinder94** [comment]
@PtrDr did you make sure to click on the "Change settings for all users" button ?

The first time i tried the workaround, i forgot this step and it wouldn't work.

The second time, I did not forgot it and i'm on a 4 Hours long synergy session without any problems

**Comment by PtrDr** [comment]
@sindwinder94  Thank you for the suggestion. It is quite a long time ago that I moved from Synergy to Mouse-without-borders, which does everything I need very well, with no problems. It even allows me to use either mouse/keyboard on either computer, which is an additional advantage. Since I am using only windows at present, it is a satisfactory solution for the time being. I expect that once I start using a combination of Os'es, Synergy will again be an interesting option.

All this to say that since I have not used Synergy for a while, so I cannot remember whether I checked the "Change settings for all users" as you suggest.  However, the additional difficulty with the work-arounds for me (and some others apparently) was that it made many of the screens on my Server computer too small, -- to the point of being impossible to read. So while the mouse went *partly* back to expected behaviour, many applications were unusable.

So I will have to wait until the Synergitics have really solved the problem, and it will work again just as it used to, At that point, I will move back to Synergy, and begin to support them financially again.

I do appreciate your suggestion, and hope that it will work for some of the other users of this program.

**Comment by akotulu** [comment]
This bug persist on Windows 10 build 10162.
Monitors:
Benq BL3201PT (3840x2160@150%)
Macbook Pro 2014 Mid

Setting synergy.exe and synergyd.exe property "Disable display scaling on high DPI settings" for all user solved to issue.

**Comment by JourneymanGeek** [comment]
I tried the workaround, turning off display scaling for those synergy.exe and synergyd.exe and it did not work for me for me. I tried this on both the 1.7.3 release version and Nightly 8ff44d2, with a windows 8.1 server running a UHD display (A dell P2715Q, if it matters, at the default 125% scaling) and a fedora 22 client (With a 1600x900 monitor initially, tho, I swapped over to a 1280x720 display that's bigger) , both with the same versions  . Looking at the logs on the server - its obvious what the issue is for me - 

    [2015-07-20T08:44:07] INFO: watchdog status: ok
    [2015-07-20T08:44:10] INFO: accepted client connection
    [2015-07-20T08:44:10] INFO: client "phoebe" has connected
    [2015-07-20T08:44:13] INFO: switch from "Nyx" to "phoebe" at 1919,739
    [2015-07-20T08:44:13] INFO: leaving screen
    [2015-07-20T08:44:22] INFO: client "phoebe" has disconnected
    [2015-07-20T08:44:22] INFO: jump from "phoebe" to "Nyx" at 1280,720
    [2015-07-20T08:44:22] INFO: entering screen

I've connected, lost the mouse of my server, moved the client mouse to kill it. Looks like no matter where I move the mouse on the server, its trying to go to an invalid range on the client. I'd guess the solution (which may be harder than it sounds, I'm no coder ;) would be to be aware of the physical display resolutions of the clients and ensure that you never jump to an invalid range on the client.

**Comment by sauri** [comment]
I got this issue after upgrading the synergy-server machine from Win 8.1 to Win 10 (client is OS X 10.10, though it probably is not relevant). The workaround didn't work for me so I started experimenting. What did the trick was turning on both "Disable display scaling on high DPI settings" AND "Compatibility mode: Windows 7" on synergys.exe for all users.

**Comment by fmalekpour** [comment]
Same problem here after upgrading to Win10, no matter what I do, it won't work.

**Comment by PtrDr** [comment]
Too bad that the issue is not yet resolved. Until there is a solution, I will have to remain with Mouse-without-borders..

**Comment by dynamicscrmbiz** [comment]
@PtrDr I was facing the same issues as you do. @nbolton mentioned that the synergy client and server must be restarted using the GUI. File-> Stop/Start options. That trick worked for me. restarting the applications did not.
I would suggest you give it another shot. Just goto properties for synergy executables, click on change settings for all users button and set the Windows 7 Compatibility mode and check the "Disable Display Scaling for high DPI" checkbox.
Restart the synergy client and server must be restarted using the GUI. File-> Stop/Start options.
HTH

**Comment by fmalekpour** [comment]
I checked the "Disable Display Scaling for high DPI" and compatibility for Windows 7 for "All Users" on all executable files in synergy folder. Restarted the computer and did a GUI -> File -> Stop and Start. It does not work, mouse keep stuck at the bottom right corner of the client.

Here is my configuration:

Server: 
    Windows 10, 
    screen resolution: 2560x1440
    DPI: 125%

Client:
    Mac OSX 10.10.4
    screen resolution: 2560x1440

I tested with moving mouse to the edge of screen to move to other screen and also change the screens using shortcuts, both have the same result. If I change the DPI of the server to 100% it works fine, but then everything is so small on the Windows 10 screen.

**Comment by fmalekpour** [comment]
More info:
In debug mode, I get a lot of these lines when switching to client:

[2015-08-06T17:49:22] DEBUG: SetCursorPos did not work; using fakeMouseMove instead

**Comment by PtrDr** [comment]
@dynamicscrmbiz Thank you for the suggestion. However, I had to uninstall the program as it was really interfering frequently with my work every day, So I am unable to try things out without uninstalling MWB and reinstalling Synergy. Now that its status has been raised to priority-urgent, perhaps some new insights will present themselves.  

What I found to be peculiar when it first occurred is that it just happened. All was working well, then it wasn't. As far as I can remember, I did not do anything to provoke it. It might have been a Windows update, or something -- although others here have reported issues with setups that are different from mine... So I just don't know. Good luck to the gurus!

**Comment by fmalekpour** [comment]
Finally after hours of testing, this one fixed the problem for me:
http://windows10_dpi_blurry_fix.xpexplorer.com/

**Comment by rotoiti** [comment]
Having the same problem after installing Windows 10 over Windows 7 (which worked fine). Workaround from the first post worked fine. 3840x2160 on Dell P2715Q, 150% scaling.

**Comment by craigdods** [comment]
Just confirming this still exists on Windows 10 (upgraded from 7 with same hardware). Utilizing the " "Disable Display Scaling for high DPI" and compatibility for Windows 7 for "All Users"" workaround resolves the issue on Win10 (build 10240)

**Comment by Cyph3r** [comment]
Confirmed everything in this thread. 4k on main monitor.
"Disable Display Scaling for high DPI" on 4k server / main screen resolved the problem.
Now I don't need to return the new screen or break something.
Cheers! :D

**Comment by vhogemann** [comment]
Confirming bug for Windows 10 (server), FullHD screen on Surface Pro 2, and external display also at FullHD. Ubuntu client.

Disabling Display Scaling for high DPI fixed this

**Comment by XinyuHou** [comment]
Related to #5030

Fixed by 5910ebe

**Comment by chevex** [comment]
Still getting this bug. Windows 10 Anniversary Update and Macbook Pro 2013 as client. Had to set compatibility settings like others described to "fix" it.

**Comment by PtrDr** [comment]
Sad to see that the problems persist. I have not made the jump to Win 10 on my daily-use machines; Win 7 doing just fine. Mouse without Borders also behaving. 

But I  have recently acquired a refurbished laptop that came with Win 10 on it. I have also dragged out an old, unused laptop (8 years old) and put Linux Mint on it. Eventually when I have all of them going, I will go back to trying out Synergy. Perhaps by that time this will be happily resolved and all this discussion will simply be an historical record of a particularly nasty creepy-crawly insect.

Good luck to the Synergetic Gurus.

**Comment by nlyan** [comment]
Reopening. Related issues that need attention that seem to related to this : #5590 and #5186

**Comment by WhiskeyBravo** [comment]
Just diagnosed and found this issue using Sierra (client) + Win10 (server) on a new laptop (150% HiDPI recommended).  Both client and server running 1.8.3 stable with OS appropriate builds.

**Comment by nlyan** [comment]
Could anyone experiencing DPI scaling related issues on Windows 10 please try this build and let us know if there any changes in behaviour?

http://symless.com/nightly?filter=1.8.4-rc1-e6a3caa

**Comment by WhiskeyBravo** [comment]
This build appears to fix the issue.  After upgrading to the nightly, my previous compatibility settings to disable DPI scaling were still applied so I removed them.  After installing the nightly, removing compat settings, and  then rebooting it is working well.  I did not upgrade the client (MacOS Sierra).
I took screenshots of the existing setup to confirm config.
<img width="788" alt="capture2" src="https://cloud.githubusercontent.com/assets/29103/19111797/b78537d0-8b01-11e6-9598-1afb6989b408.PNG">
<img width="773" alt="capture1" src="https://cloud.githubusercontent.com/assets/29103/19111798/b78979a8-8b01-11e6-95d0-19185f65b70e.PNG">

**Comment by dvv47** [comment]
This updates fixes movement rigth and down. But now speed on client computer too high.
My main monitor have 250% scaling and client 100%
And looks like on client speed must be in 2.5 times slower

**Comment by nlyan** [comment]
@WhiskeyBravo thanks for the feedback. we just disabled DPI scaling at source in this build.

@dvv47 thanks

**Comment by nlyan** [comment]
@dvv47 Could you try this build? 

http://symless.com/nightly?filter=b112617

It'll be there as soon as the buildbot is done. Would be much appreciated.

**Comment by dvv47** [comment]
@nlyan Thanks, with build 112617 all works as expected.
With mouse and touchpad.

**Comment by PtrDr** [comment]
I noticed that in the discussion people were referring to Win 10. Does it apply to Win 10 Home as well as Pro and other types of Win variations? And the recent W10 upgrades? Is it also compatible with Win 7?

**Comment by nlyan** [comment]
@PtrDr as far as I am able to determine this was caused by the changes in behaviour with respect to DPI scaling across Windows versions 8, 8.1 and 10. Home vs Pro won't make a difference.

**Comment by nlyan** [comment]
@PtrDr

I don't know for sure, all I can suggest is you try Synergy again :)

https://symless.com/nightly?filter=1.8.4-rc3

**Comment by giammin** [comment]
this problem came up again on 1.8.8

**Comment by jongrant** [comment]
This bug is back in Windows 10 r1709. The fix that eventually worked for me was to remove the "Run in compatibility mode for: Windows 7" setting on synergys.exe. Unfortunately the configuration tool forces this setting back on any time you open it.
