### ISSUE TITLE
Mouse jumps back to host when client is asking for admin privileges

### ISSUE THREAD

**Issue by bumbummen99** [symless/synergy#6073]
### Operating Systems ###

Server: Windows 10 1607 Pro
Client: Windows 10 1607 Home

### Synergy Version ###

1.8.8 25a8cb2

### Steps to reproduce bug ###

1. Run something that will request admin privileges (such as uninstalling a program) on a client device.
3. Mouse jumps back to the exact center of the host's main screen (on multi screen setup).

### Other info ###

* When did the problem start to occur? Always
* Is there a way to work around it? No, you have to use the clients mouse to either allow or deny the request.
* Does this bug prevent you from using Synergy entirely? It makes synergy look very cheap

I dont know if there is a possible fix for that but its really annoying.

**Comment by nlyan** [comment]
Have you tried setting Elevation 'Always' in settings?

**Comment by bumbummen99** [comment]
I have not tried that yet but i will when i am at home. Can you provide more infromation on that option?

**Comment by aminor00** [comment]
Thanks for the tip @nlyan, setting 'Elevation' to 'Always' fixed it for me on the client (Mac server, Windows 10 client)

**Comment by XinyuHou** [comment]
Close as it's have been resolved

**Comment by bumbummen99** [comment]
Still can't find information in docsabout this setting. Please provide closer information.
